# Generated by Django 5.0 on 2023-12-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('yop', models.PositiveBigIntegerField()),
                ('skill', models.CharField(max_length=100)),
                ('percentage', models.PositiveIntegerField()),
                ('mockRating', models.CharField(max_length=5)),
            ],
        ),
    ]
